services:
  app:
    image: front-end-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: front-end-dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
